// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_delta_v
NumericMatrix find_delta_v(NumericMatrix v, NumericMatrix dist_mat);
RcppExport SEXP _morevac_find_delta_v(SEXP vSEXP, SEXP dist_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    rcpp_result_gen = Rcpp::wrap(find_delta_v(v, dist_mat));
    return rcpp_result_gen;
END_RCPP
}
// infect_cpp_2
List infect_cpp_2(NumericMatrix inf_history, NumericMatrix years_since_last_vac, NumericMatrix vac_history, NumericMatrix suscept_mat, NumericMatrix x, NumericMatrix ages_mat, NumericMatrix delta_v, NumericMatrix dist_mat, NumericVector gammas, NumericVector foi, double wane_rate, double epsilon);
RcppExport SEXP _morevac_infect_cpp_2(SEXP inf_historySEXP, SEXP years_since_last_vacSEXP, SEXP vac_historySEXP, SEXP suscept_matSEXP, SEXP xSEXP, SEXP ages_matSEXP, SEXP delta_vSEXP, SEXP dist_matSEXP, SEXP gammasSEXP, SEXP foiSEXP, SEXP wane_rateSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type inf_history(inf_historySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type years_since_last_vac(years_since_last_vacSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type vac_history(vac_historySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type suscept_mat(suscept_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ages_mat(ages_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type delta_v(delta_vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gammas(gammasSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type foi(foiSEXP);
    Rcpp::traits::input_parameter< double >::type wane_rate(wane_rateSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(infect_cpp_2(inf_history, years_since_last_vac, vac_history, suscept_mat, x, ages_mat, delta_v, dist_mat, gammas, foi, wane_rate, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// initialize_pop_cpp
List initialize_pop_cpp(int n, int nyears, NumericVector init_ages, int max_age);
RcppExport SEXP _morevac_initialize_pop_cpp(SEXP nSEXP, SEXP nyearsSEXP, SEXP init_agesSEXP, SEXP max_ageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nyears(nyearsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type init_ages(init_agesSEXP);
    Rcpp::traits::input_parameter< int >::type max_age(max_ageSEXP);
    rcpp_result_gen = Rcpp::wrap(initialize_pop_cpp(n, nyears, init_ages, max_age));
    return rcpp_result_gen;
END_RCPP
}
// lifetime_infections_cpp
int lifetime_infections_cpp(int a, int lifetime_inf, int inf_stat);
RcppExport SEXP _morevac_lifetime_infections_cpp(SEXP aSEXP, SEXP lifetime_infSEXP, SEXP inf_statSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type lifetime_inf(lifetime_infSEXP);
    Rcpp::traits::input_parameter< int >::type inf_stat(inf_statSEXP);
    rcpp_result_gen = Rcpp::wrap(lifetime_infections_cpp(a, lifetime_inf, inf_stat));
    return rcpp_result_gen;
END_RCPP
}
// vaccinate_cpp_2
List vaccinate_cpp_2(NumericMatrix vac_hist_mat, NumericMatrix v, IntegerMatrix ages_mat, IntegerVector vac_this_year, NumericVector vac_cov, double take, double rho, int vac_strategy);
RcppExport SEXP _morevac_vaccinate_cpp_2(SEXP vac_hist_matSEXP, SEXP vSEXP, SEXP ages_matSEXP, SEXP vac_this_yearSEXP, SEXP vac_covSEXP, SEXP takeSEXP, SEXP rhoSEXP, SEXP vac_strategySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vac_hist_mat(vac_hist_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type ages_mat(ages_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type vac_this_year(vac_this_yearSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vac_cov(vac_covSEXP);
    Rcpp::traits::input_parameter< double >::type take(takeSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type vac_strategy(vac_strategySEXP);
    rcpp_result_gen = Rcpp::wrap(vaccinate_cpp_2(vac_hist_mat, v, ages_mat, vac_this_year, vac_cov, take, rho, vac_strategy));
    return rcpp_result_gen;
END_RCPP
}
// vaccine_update_cpp
List vaccine_update_cpp(NumericMatrix drift, double threshold, double vac_protect);
RcppExport SEXP _morevac_vaccine_update_cpp(SEXP driftSEXP, SEXP thresholdSEXP, SEXP vac_protectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type drift(driftSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type vac_protect(vac_protectSEXP);
    rcpp_result_gen = Rcpp::wrap(vaccine_update_cpp(drift, threshold, vac_protect));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_morevac_find_delta_v", (DL_FUNC) &_morevac_find_delta_v, 2},
    {"_morevac_infect_cpp_2", (DL_FUNC) &_morevac_infect_cpp_2, 12},
    {"_morevac_initialize_pop_cpp", (DL_FUNC) &_morevac_initialize_pop_cpp, 4},
    {"_morevac_lifetime_infections_cpp", (DL_FUNC) &_morevac_lifetime_infections_cpp, 3},
    {"_morevac_vaccinate_cpp_2", (DL_FUNC) &_morevac_vaccinate_cpp_2, 8},
    {"_morevac_vaccine_update_cpp", (DL_FUNC) &_morevac_vaccine_update_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_morevac(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
