// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// infect_cpp
int infect_cpp(double susceptibility, double foi, double randnum_inf);
RcppExport SEXP _morevac_infect_cpp(SEXP susceptibilitySEXP, SEXP foiSEXP, SEXP randnum_infSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type susceptibility(susceptibilitySEXP);
    Rcpp::traits::input_parameter< double >::type foi(foiSEXP);
    Rcpp::traits::input_parameter< double >::type randnum_inf(randnum_infSEXP);
    rcpp_result_gen = Rcpp::wrap(infect_cpp(susceptibility, foi, randnum_inf));
    return rcpp_result_gen;
END_RCPP
}
// lifetime_infections_cpp
int lifetime_infections_cpp(int a, int lifetime_inf, int inf_stat);
RcppExport SEXP _morevac_lifetime_infections_cpp(SEXP aSEXP, SEXP lifetime_infSEXP, SEXP inf_statSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type lifetime_inf(lifetime_infSEXP);
    Rcpp::traits::input_parameter< int >::type inf_stat(inf_statSEXP);
    rcpp_result_gen = Rcpp::wrap(lifetime_infections_cpp(a, lifetime_inf, inf_stat));
    return rcpp_result_gen;
END_RCPP
}
// suscept_func_cpp
double suscept_func_cpp(int inf_history, int vac_history, double gamma, double drift_x, double drift_v, double wane_rate, int version, int constant);
RcppExport SEXP _morevac_suscept_func_cpp(SEXP inf_historySEXP, SEXP vac_historySEXP, SEXP gammaSEXP, SEXP drift_xSEXP, SEXP drift_vSEXP, SEXP wane_rateSEXP, SEXP versionSEXP, SEXP constantSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type inf_history(inf_historySEXP);
    Rcpp::traits::input_parameter< int >::type vac_history(vac_historySEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type drift_x(drift_xSEXP);
    Rcpp::traits::input_parameter< double >::type drift_v(drift_vSEXP);
    Rcpp::traits::input_parameter< double >::type wane_rate(wane_rateSEXP);
    Rcpp::traits::input_parameter< int >::type version(versionSEXP);
    Rcpp::traits::input_parameter< int >::type constant(constantSEXP);
    rcpp_result_gen = Rcpp::wrap(suscept_func_cpp(inf_history, vac_history, gamma, drift_x, drift_v, wane_rate, version, constant));
    return rcpp_result_gen;
END_RCPP
}
// vaccinate_cpp
int vaccinate_cpp(int prior_vac, int vac_this_year, double vac_cov, int age, double rho, double randnum_vac, int actual_year, int start_vac_year, int start_vac_age);
RcppExport SEXP _morevac_vaccinate_cpp(SEXP prior_vacSEXP, SEXP vac_this_yearSEXP, SEXP vac_covSEXP, SEXP ageSEXP, SEXP rhoSEXP, SEXP randnum_vacSEXP, SEXP actual_yearSEXP, SEXP start_vac_yearSEXP, SEXP start_vac_ageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type prior_vac(prior_vacSEXP);
    Rcpp::traits::input_parameter< int >::type vac_this_year(vac_this_yearSEXP);
    Rcpp::traits::input_parameter< double >::type vac_cov(vac_covSEXP);
    Rcpp::traits::input_parameter< int >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type randnum_vac(randnum_vacSEXP);
    Rcpp::traits::input_parameter< int >::type actual_year(actual_yearSEXP);
    Rcpp::traits::input_parameter< int >::type start_vac_year(start_vac_yearSEXP);
    Rcpp::traits::input_parameter< int >::type start_vac_age(start_vac_ageSEXP);
    rcpp_result_gen = Rcpp::wrap(vaccinate_cpp(prior_vac, vac_this_year, vac_cov, age, rho, randnum_vac, actual_year, start_vac_year, start_vac_age));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_morevac_infect_cpp", (DL_FUNC) &_morevac_infect_cpp, 3},
    {"_morevac_lifetime_infections_cpp", (DL_FUNC) &_morevac_lifetime_infections_cpp, 3},
    {"_morevac_suscept_func_cpp", (DL_FUNC) &_morevac_suscept_func_cpp, 8},
    {"_morevac_vaccinate_cpp", (DL_FUNC) &_morevac_vaccinate_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_morevac(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
