# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

infect_cpp <- function(susceptibility, foi, randnum_inf) {
    .Call(`_morevac_infect_cpp`, susceptibility, foi, randnum_inf)
}

lifetime_infections_cpp <- function(a, lifetime_inf, inf_stat) {
    .Call(`_morevac_lifetime_infections_cpp`, a, lifetime_inf, inf_stat)
}

suscept_func_cpp <- function(inf_history, vac_history, gamma, drift_x, drift_v, wane_rate, version, constant) {
    .Call(`_morevac_suscept_func_cpp`, inf_history, vac_history, gamma, drift_x, drift_v, wane_rate, version, constant)
}

vaccinate_cpp <- function(prior_vac, vac_this_year, vac_cov, take, age, rho, randnum_vac, actual_year, start_vac_year, start_vac_age) {
    .Call(`_morevac_vaccinate_cpp`, prior_vac, vac_this_year, vac_cov, take, age, rho, randnum_vac, actual_year, start_vac_year, start_vac_age)
}

